SELECT * FROM ignug.ContenidosActividades;
Insert Into ContenidosActividades ( id, idContenidoElementos, idSilaboEvidenciasRa, tipo, horasClase) Values (1,1,1,'Null',10);
Insert Into ContenidosActividades ( id, idContenidoElementos, idSilaboEvidenciasRa, tipo, horasClase) Values (2,2,2,'Null',11);
Insert Into ContenidosActividades ( id, idContenidoElementos, idSilaboEvidenciasRa, tipo, horasClase) Values (3,3,3,'Null',12);
Insert Into ContenidosActividades ( id, idContenidoElementos, idSilaboEvidenciasRa, tipo, horasClase) Values (4,4,4,'Null',13);
Insert Into ContenidosActividades ( id, idContenidoElementos, idSilaboEvidenciasRa, tipo, horasClase) Values (5,5,5,'Null',14);
Insert Into ContenidosActividades ( id, idContenidoElementos, idSilaboEvidenciasRa, tipo, horasClase) Values (6,6,6,'Null',15);
Insert Into ContenidosActividades ( id, idContenidoElementos, idSilaboEvidenciasRa, tipo, horasClase) Values (7,7,7,'Null',16);
Insert Into ContenidosActividades ( id, idContenidoElementos, idSilaboEvidenciasRa, tipo, horasClase) Values (8,8,8,'Null',17);
Insert Into ContenidosActividades ( id, idContenidoElementos, idSilaboEvidenciasRa, tipo, horasClase) Values (9,9,9,'Null',18);
Insert Into ContenidosActividades ( id, idContenidoElementos, idSilaboEvidenciasRa, tipo, horasClase) Values (10,10,10,'Null',19);
